### ISSUE TITLE
Problema con los directorios

### ISSUE THREAD

**Issue by salvanescki** [juanicolombo97/AlgoChess#23]
Hola profe, queríamos saber si los directorios (en la branch posicion) están bien ordenados para maven, porque surgieron algunos problemas y no sabemos si es porque hicimos mal el refactor o por otros motivos.

**Comment by tomasBustamante** [comment]
Hola:

Hay un problema en la [línea 41 del archivo pom.xml](https://github.com/juanicolombo97/AlgoChess/blob/Posicion/pom.xml#L41). No está indicado el número de versión de JUnit 5.

Reemplazando donde dice "RELEASE" por "5.5.2" pude correr las pruebas con Maven sin problemas. Cualquier cosa fíjense en [este ejemplo](https://github.com/tomasBustamante/Pokemon/blob/master/pom.xml).

Saludos,
Tomás
