### ISSUE TITLE
Segunda entrega

### ISSUE THREAD

**Issue by tomasBustamante** [juanicolombo97/AlgoChess#25]
¿Se fueron? Estoy en la 403.

**Comment by salvanescki** [comment]
Disculpe, me había olvidado que nuestras entregas eran los martes. Igualmente puedo ir los jueves de entregas a la noche. Siento los inconvenientes, podemos hacer la entrega mañana?

**Comment by tomasBustamante** [comment]
Mañana no voy. Lo vemos el martes.
